version: "3.8"
services:
  backend:
    build: ../backend
    ports:
      - "3000:3000"
  python-ai:
    build: ../python-ai
    ports:
      - "8001:8001"
  frontend:
    build: ../frontend
    ports:
      - "5173:5173"
